# Default values for OSO Services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-oso-ptt-services

global:
  minikube: true
  cluster_domain: techops.internal.skao.int

rest:
  component: rest
  function: oso-services
  domain: operations
  logLevel: INFO
  enabled: true
  production: false
  image:
    registry: gitlab.com  
    image: ska-telescope/oso/ska-oso-ptt-services/ska-oso-ptt-services  
    tag: 0.3.0-dev.cd8625bbc # Defaults to the chart appVersion if not set
    pullPolicy: IfNotPresent
  oda:
    backendType: postgres
    postgres: # The below values are used to set environment variables that are used in the ODA Repository. If they are not set then the defaults defined by the ODA will be used.
      host: ~
      port: ~
      user: ~
      password: secretpassword
      db:
        name: ~
  use_skuid: true
  skuid:
    url:
  ingress:
    enabled: true

nodeSelector: {}

affinity: {}

tolerations: []
