ProjectStatusHistory:
  type: object
  required:
    - prj_version
    - previous_status
    - current_status
  properties:
    prj_version:
      default: 1
      title: Project Version
      type: integer
    previous_status:
      description: Previous Status of the Project Entity.
      example: Draft
      type: string
    current_status:
      description: Current Status of the Project Entity.
      example: Ready
      type: string
   
    