ProjectStatusHistory:
  type: object
  required:
    - version
    - previous_status
    - current_status
  properties:
    version:
      description: Version of the Project Entity.
      example: 1
      type: integer
    previous_status:
      description: Previous Status of the Project Entity.
      example: Draft
      type: string
    current_status:
      description: Current Status of the Project Entity.
      example: Ready
      type: string
   
    