SBDStatusHistory:
  type: object
  required:
    - sbd_version
    - previous_status
    - current_status
  properties:
    sbd_version:
      default: 1
      title: SBD Version
      type: integer
    previous_status:
      description: Previous Status of the SBD Entity.
      example: Draft
      type: string
    current_status:
      description: Current Status of the SBD Entity.
      example: Complete
      type: string
    
   
