SBDStatusHistory:
  type: object
  required:
    - previous_status
    - current_status
  properties:
    previous_status:
      description: Previous Status of the SBD Entity.
      example: Draft
      type: string
    current_status:
      description: Current Status of the SBD Entity.
      example: Complete
      type: string


