SBIStatusHistory:
  type: object
  required:
    - previous_status
    - current_status
  properties:
    previous_status:
      description: Previous Status of the SBI Entity.
      example: Created
      type: string
    current_status:
      description: Current Status of the SBI Entity.
      example: Executing
      type: string


