apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-oso-ptt-services.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-ptt-services.labels" . | indent 4 }}
    component:  {{ template "ska-oso-ptt-services.name" . }}
    domain: environment
    function: ska-oso-ptt-services-environment
    intent: production
data:
  PRODUCTION: {{ .Values.rest.production | quote }}
  LOG_LEVEL: {{ .Values.rest.logLevel }}
  KUBE_NAMESPACE: {{ .Release.Namespace }}
  ODA_BACKEND_TYPE: {{ .Values.rest.oda.backendType }}
   {{ if .Values.rest.oda.postgres.host }}
  POSTGRES_HOST: {{ .Values.rest.oda.postgres.host }}
  {{ else }}
  POSTGRES_HOST: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.{{ .Values.global.cluster_domain }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.port }}
  POSTGRES_PORT: {{ .Values.rest.oda.postgres.port | quote }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.db.name }}
  POSTGRES_DB_NAME: {{ .Values.rest.oda.postgres.db.name }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.user }}
  ADMIN_POSTGRES_USER: {{ .Values.rest.oda.postgres.user }}
  {{ end }}
  {{ if .Values.rest.skuid.url }}
  SKUID_URL: {{ .Values.rest.skuid.url }}
  {{ else }}
  SKUID_URL: ska-ser-skuid-{{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.{{ .Values.global.cluster_domain }}:9870
  {{ end }}

