apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kafka-data
  name: kafka-data
  namespace: ska-oso-ptt-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
