apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: ska-oso-ptt-services
spec:
  serviceName: zookeeper-service
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      hostname: zookeeper
      subdomain: zookeeper-service
      containers:
        - name: zookeeper
          image: docker.io/bitnami/zookeeper:3.9
          env:
            - name: ZOO_ENABLE_AUTH
              value: "yes"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOO_SERVER_ID
              value: "1"
            - name: ZOO_TICK_TIME
              value: "2000"
          ports:
            - name: client
              containerPort: 2181
            - name: follower
              containerPort: 2888
            - name: election
              containerPort: 3888
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 20
            periodSeconds: 15
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper
              
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-data
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: ska-oso-ptt-services
spec:
  type: ClusterIP 
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: follower
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
