global:
  cluster_domain: techops.internal.skao.int

ska-oso-ptt-services:
  rest:
    oda:
      backendType: postgres

ska-db-oda-umbrella:
  ska-db-oda:
    enabled: true
    secretProvider:
      enabled: true
    rest:
      enabled: true # ska-oso-services d
      ingress:
        enabled: true
      backend:
        type: postgres
        postgres:
          host:
  postgresql:
    enabled: true
  pgadmin4:
    enabled: true

