global:
  cluster_domain: techops.internal.skao.int

ska-oso-ptt-services:
  rest:
    oda:
      backendType: postgres

ska-db-oda-umbrella:
  enabled: true
  ska-db-oda:
    enabled: true 
  postgresql:
    enabled: true
  pgadmin4:
    enabled: true
  ska-ser-skuid:
    skuid:
      enabled: true




