global:
  cluster_domain: techops.internal.skao.int

ska-oso-ptt-services:
  rest:
    oda:
      backendType: postgres

ska-db-oda-umbrella:
  enabled: true
  ska-db-oda:
    rest:
      enabled: true 
  postgresql:
    enabled: true




