openapi: 3.0.0
info:
  title: Project Tracking Tool API
  description: 'This OpenAPI document defines the API for the Project Tracking Tool (PTT) REST service'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: 1.0.0
servers:
# This default is overwritten when the application is deployed to include the actual namespace if it is different to the 'ska-osd' default
- url: /ska-oso-ptt-services/ptt/api/v1
paths:
  /sbds:
    get:
      summary: Get SBDefinition filter by the query parameter
      description: |
        Retrieves the SBDefinitions which match the query parameters.
        Currently only a single query field is permitted, eg user, entity_id or created_on - 
        extra parameters passed to the request will be ignored, with an order of 
        precedence of user > created_on > modified_on. Also requests without
        parameters will return an error rather than returning all objects. This behaviour will
        change in the future..
      operationId: ska_oso_ptt_services.api.get_sbds
      parameters:
        - $ref: '#/components/parameters/user'
        - $ref: '#/components/parameters/MatchType'
        - $ref: '#/components/parameters/createdBefore'
        - $ref: '#/components/parameters/createdAfter'
        - $ref: '#/components/parameters/modifiedBefore'
        - $ref: '#/components/parameters/modifiedAfter'
        - $ref: '#/components/parameters/entity_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "400":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/InternalServerError'
  

components:
  parameters:
    user:
      in: query
      name: user
      schema:
        type: string
      required: false
    MatchType:
      in: query
      name: match_type
      schema:
        type: string
        enum: [ equals, starts_with, contains]
        default: equals
      required: false
    createdBefore:
      in: query
      name: created_before
      schema:
        type: string
      required: false
      example: 2022-03-28T15:43:53.971548+00:00
    createdAfter:
      in: query
      name: created_after
      schema:
        type: string
      required: false
      example: 2022-03-28T15:43:53.971548+00:00
    modifiedBefore:
      in: query
      name: last_modified_before
      schema:
        type: string
      required: false
      example: 2022-03-28T15:43:53.971548+00:00
    modifiedAfter:
      in: query
      name: last_modified_after
      schema:
        type: string
      required: false
      example: 2022-03-28T15:43:53.971548+00:00
    entity_id:
      in: query
      name: entity_id
      schema:
        type: string
      required: false
  responses:
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BadRequest:
      description: Bad Request, eg validation of against OpenAPI spec failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestResponse'
    UnprocessableEntity:
      description: Unprocessable Entity, semantic error in request eg mismatched IDs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    BadRequestResponse:
      type: object
      properties:
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
    ErrorResponse:
      type: object
      properties:
        title:
          type: string
        detail:
          type: string
        traceback:
          type: object
          properties:
            key:
              type: string
            type:
              type: string
            full_traceback:
              type: string
